name: release fc-docker images

on:
  release:
    types: [created]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
  ALIYUN_DOCKER_USER: ${{secrets.ALIYUN_DOCKER_USER}}
  ALIYUN_DOCKER_PASS: ${{secrets.ALIYUN_DOCKER_PASS}}

jobs:
  release-images:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 16
      fail-fast: false
      matrix:
        runtime:
          [
            java8,
            java11,
            nodejs6,
            nodejs8,
            nodejs10,
            nodejs12,
            nodejs14,
            nodejs16,
            python2.7,
            python3.6,
            python3.9,
            php7.2,
            dotnetcore2.1,
            custom,
            go1,
            python3.10,
            custom.debian10,
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: build-push to dockerhub
        run: |
          make build-push RUNTIME=${{ matrix.runtime }} TAG=$(head -n 1 LATEST) VARIANT=base
          make build-push RUNTIME=${{ matrix.runtime }} TAG=$(head -n 1 LATEST) VARIANT=build
          make build-push RUNTIME=${{ matrix.runtime }} TAG=$(head -n 1 LATEST) VARIANT=run
          make build-push RUNTIME=${{ matrix.runtime }} TAG=latest VARIANT=base
          make build-push RUNTIME=${{ matrix.runtime }} TAG=latest VARIANT=build
          make build-push RUNTIME=${{ matrix.runtime }} TAG=latest VARIANT=run
      - name: build-push to acr
        run: |
          make build-push RUNTIME=${{ matrix.runtime }} TAG=$(head -n 1 LATEST) REGISTRY="registry.cn-beijing.aliyuncs.com" VARIANT=base
          make build-push RUNTIME=${{ matrix.runtime }} TAG=$(head -n 1 LATEST) REGISTRY="registry.cn-beijing.aliyuncs.com" VARIANT=build
          make build-push RUNTIME=${{ matrix.runtime }} TAG=$(head -n 1 LATEST) REGISTRY="registry.cn-beijing.aliyuncs.com" VARIANT=run
          make build-push RUNTIME=${{ matrix.runtime }} TAG=latest REGISTRY="registry.cn-beijing.aliyuncs.com" VARIANT=base
          make build-push RUNTIME=${{ matrix.runtime }} TAG=latest REGISTRY="registry.cn-beijing.aliyuncs.com" VARIANT=build
          make build-push RUNTIME=${{ matrix.runtime }} TAG=latest REGISTRY="registry.cn-beijing.aliyuncs.com" VARIANT=run
